// Code generated by goyacc g.y. DO NOT EDIT.

//line g.y:2
package calc

import __yyfmt__ "fmt"

//line g.y:2

import (
	"fmt"
	"strconv"
)

// 语法树节点类型
type NodeType int

const (
	NodeProgram NodeType = iota
	NodeVarDecl
	NodeAssign
	NodeExpr
	NodeBinOp
	NodeUnaryOp
	NodeTernary
	NodeIdent
	NodeNumber
	NodeBool
)

// 语法树节点
type Node struct {
	Type     NodeType
	Target   exprType
	Token    string
	Children []*Node
}

// 全局变量存储解析结果
var parseResult *Node

//line g.y:37
type yySymType struct {
	yys  int
	node *Node
	str  string
	num  float64
	bool bool
}

const IDENT = 57346
const NUMBER = 57347
const BOOLEAN = 57348
const INT = 57349
const FLOAT = 57350
const BOOL = 57351
const TRUE = 57352
const FALSE = 57353
const ASSIGN = 57354
const SEMICOLON = 57355
const COMMA = 57356
const LPAREN = 57357
const RPAREN = 57358
const QUESTION = 57359
const COLON = 57360
const PLUS = 57361
const MINUS = 57362
const MULTIPLY = 57363
const DIVIDE = 57364
const MOD = 57365
const POWER = 57366
const AND = 57367
const OR = 57368
const NOT = 57369
const LT = 57370
const LE = 57371
const GT = 57372
const GE = 57373
const EQ = 57374
const NE = 57375
const UMINUS = 57376
const UPLUS = 57377

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"BOOLEAN",
	"INT",
	"FLOAT",
	"BOOL",
	"TRUE",
	"FALSE",
	"ASSIGN",
	"SEMICOLON",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"QUESTION",
	"COLON",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"MOD",
	"POWER",
	"AND",
	"OR",
	"NOT",
	"LT",
	"LE",
	"GT",
	"GE",
	"EQ",
	"NE",
	"UMINUS",
	"UPLUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line g.y:404

// 词法分析器接口
type Lexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

// 简单的词法分析器实现
type SimpleLexer struct {
	input string
	pos   int
	line  int
}

func NewLexer(input string) *SimpleLexer {
	return &SimpleLexer{input: input, pos: 0, line: 1}
}

func (l *SimpleLexer) Error(s string) {
	// fmt.Printf("语法错误 (行 %d): %s\n", l.line, s)
}

func (l *SimpleLexer) Lex(lval *yySymType) int {
	for l.pos < len(l.input) {
		ch := l.input[l.pos]

		// 跳过空白字符
		if ch == ' ' || ch == '\t' || ch == '\r' {
			l.pos++
			continue
		}

		if ch == '\n' {
			l.line++
			l.pos++
			continue
		}

		// 识别各种token
		switch ch {
		case ';':
			l.pos++
			return SEMICOLON
		case '=':
			if l.pos+1 < len(l.input) && l.input[l.pos+1] == '=' {
				l.pos += 2
				return EQ
			}
			l.pos++
			return ASSIGN
		case '(':
			l.pos++
			return LPAREN
		case ')':
			l.pos++
			return RPAREN
		case '+':
			l.pos++
			return PLUS
		case '-':
			l.pos++
			return MINUS
		case '*':
			l.pos++
			return MULTIPLY
		case '/':
			l.pos++
			return DIVIDE
		case '%':
			l.pos++
			return MOD
		case '^':
			l.pos++
			return POWER
		case ',':
			l.pos++
			return COMMA
		case '?':
			l.pos++
			return QUESTION
		case ':':
			l.pos++
			return COLON
		case '!':
			if l.pos+1 < len(l.input) && l.input[l.pos+1] == '=' {
				l.pos += 2
				return NE
			}
			l.pos++
			return NOT
		case '<':
			if l.pos+1 < len(l.input) && l.input[l.pos+1] == '=' {
				l.pos += 2
				return LE
			}
			l.pos++
			return LT
		case '>':
			if l.pos+1 < len(l.input) && l.input[l.pos+1] == '=' {
				l.pos += 2
				return GE
			}
			l.pos++
			return GT
		case '&':
			if l.pos+1 < len(l.input) && l.input[l.pos+1] == '&' {
				l.pos += 2
				return AND
			}
			// 单独的 & 字符是非法的，跳过并报告错误
			l.Error(fmt.Sprintf("unexpected character '&' at position %d", l.pos))
			l.pos++
			continue
		case '|':
			if l.pos+1 < len(l.input) && l.input[l.pos+1] == '|' {
				l.pos += 2
				return OR
			}
			// 单独的 | 字符是非法的，跳过并报告错误
			l.Error(fmt.Sprintf("unexpected character '|' at position %d", l.pos))
			l.pos++
			continue
		}

		// 识别数字
		if ch >= '0' && ch <= '9' || ch == '.' {
			return l.lexNumber(lval)
		}

		// 识别标识符和关键字
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || ch == '_' {
			return l.lexIdent(lval)
		}

		// 未识别的字符，报告错误并跳过
		l.Error(fmt.Sprintf("unexpected character '%c' at position %d", ch, l.pos))
		l.pos++
	}
	return 0 // EOF
}

func (l *SimpleLexer) lexNumber(lval *yySymType) int {
	start := l.pos
	hasDot := false

	for l.pos < len(l.input) {
		ch := l.input[l.pos]
		if ch >= '0' && ch <= '9' {
			l.pos++
		} else if ch == '.' && !hasDot {
			hasDot = true
			l.pos++
		} else {
			break
		}
	}

	numStr := l.input[start:l.pos]
	if _, err := strconv.ParseFloat(numStr, 64); err == nil {
		lval.str = numStr
		return NUMBER
	}
	return 0
}

func (l *SimpleLexer) lexIdent(lval *yySymType) int {
	start := l.pos

	for l.pos < len(l.input) {
		ch := l.input[l.pos]
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9') || ch == '_' {
			l.pos++
		} else {
			break
		}
	}

	ident := l.input[start:l.pos]
	lval.str = ident

	// 检查关键字
	switch ident {
	case "int":
		return INT
	case "float":
		return FLOAT
	case "bool":
		return BOOL
	case "true":
		lval.bool = true
		return TRUE
	case "false":
		lval.bool = false
		return FALSE
	default:
		return IDENT
	}
}

// 解析函数
func parse(input string) (*Node, error) {
	lexer := NewLexer(input)
	if yyParse(lexer) != 0 {
		return nil, fmt.Errorf("解析失败")
	}
	return parseResult, nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 81

var yyAct = [...]int8{
	9, 19, 17, 15, 6, 8, 25, 18, 10, 11,
	12, 26, 27, 36, 37, 16, 28, 33, 35, 14,
	22, 23, 38, 39, 40, 41, 34, 3, 24, 44,
	45, 46, 73, 52, 47, 20, 71, 55, 56, 58,
	54, 61, 62, 63, 64, 29, 67, 68, 69, 70,
	65, 66, 59, 60, 57, 49, 25, 53, 48, 50,
	51, 26, 27, 42, 43, 32, 28, 72, 31, 7,
	22, 23, 21, 13, 74, 5, 30, 4, 24, 2,
	1,
}

var yyPact = [...]int16{
	1, -1000, 32, -1000, -1000, -1000, -1000, 64, 53, -1000,
	-1000, -1000, -1000, 0, -7, -19, -6, 44, 8, -1000,
	10, -1000, 51, 51, 51, -1000, -1000, -1000, 51, 1,
	26, -1000, 51, 51, 51, 51, 51, 51, 51, 51,
	51, 51, 51, 51, 51, 51, 51, 51, -1000, -1000,
	-1000, -1000, 20, -1000, 63, -1000, 14, -7, -19, -6,
	-6, 44, 44, 44, 44, 8, 8, -1000, -1000, -1000,
	-1000, -1000, -1000, 51, -1000,
}

var yyPgo = [...]int8{
	0, 80, 79, 27, 77, 76, 75, 4, 0, 73,
	19, 3, 15, 2, 7, 1, 35, 72, 69,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 4, 5, 5,
	18, 18, 18, 6, 7, 8, 8, 9, 9, 10,
	10, 11, 11, 11, 12, 12, 12, 12, 12, 13,
	13, 13, 14, 14, 14, 14, 15, 15, 16, 16,
	16, 16, 17, 17, 17, 17, 17,
}

var yyR2 = [...]int8{
	0, 1, 1, 3, 1, 1, 1, 2, 1, 3,
	1, 1, 1, 3, 1, 1, 5, 1, 3, 1,
	3, 1, 3, 3, 1, 3, 3, 3, 3, 1,
	3, 3, 1, 3, 3, 3, 1, 3, 1, 2,
	2, 2, 1, 1, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -6, -7, -18, 4, -8,
	7, 8, 9, -9, -10, -11, -12, -13, -14, -15,
	-16, -17, 19, 20, 27, 5, 10, 11, 15, 13,
	-5, 4, 12, 17, 26, 25, 32, 33, 28, 29,
	30, 31, 19, 20, 21, 22, 23, 24, -16, 4,
	-16, -16, -7, -3, 14, -7, -7, -10, -11, -12,
	-12, -13, -13, -13, -13, -14, -14, -15, -15, -15,
	-15, 16, 4, 18, -8,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 4, 5, 6, 0, 42, 14,
	10, 11, 12, 15, 17, 19, 21, 24, 29, 32,
	36, 38, 0, 0, 0, 43, 44, 45, 0, 0,
	7, 8, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 39, 42,
	40, 41, 0, 3, 0, 13, 0, 18, 20, 22,
	23, 25, 26, 27, 28, 30, 31, 33, 34, 35,
	37, 46, 9, 0, 16,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:91
		{
			yyVAL.node = &Node{Type: NodeProgram, Children: []*Node{yyDollar[1].node}}
			parseResult = yyVAL.node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:99
		{
			yyVAL.node = yyDollar[1].node
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:103
		{
			// 如果第一个节点不是NodeProgram类型，创建一个包装节点
			if yyDollar[1].node.Type != NodeProgram {
				yyVAL.node = &Node{Type: NodeProgram, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
			} else {
				yyDollar[1].node.Children = append(yyDollar[1].node.Children, yyDollar[3].node)
				yyVAL.node = yyDollar[1].node
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:115
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:116
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:117
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line g.y:122
		{
			yyVAL.node = &Node{
				Type:  NodeVarDecl,
				Token: yyDollar[1].str + ":" + yyDollar[2].str,
			}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:132
		{
			yyVAL.str = yyDollar[1].str
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:136
		{
			yyVAL.str = yyDollar[1].str + "," + yyDollar[3].str
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:142
		{
			yyVAL.str = "int"
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:143
		{
			yyVAL.str = "float"
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:144
		{
			yyVAL.str = "bool"
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:149
		{
			yyVAL.node = &Node{
				Type:     NodeAssign,
				Token:    yyDollar[1].str,
				Children: []*Node{yyDollar[3].node},
			}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:159
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:164
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line g.y:168
		{
			yyVAL.node = &Node{
				Type:     NodeTernary,
				Token:    "?:",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node, yyDollar[5].node},
			}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:179
		{
			yyVAL.node = yyDollar[1].node
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:183
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "||",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:194
		{
			yyVAL.node = yyDollar[1].node
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:198
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "&&",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:209
		{
			yyVAL.node = yyDollar[1].node
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:213
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "==",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:221
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "!=",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:232
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:236
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "<",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:244
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "<=",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:252
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    ">",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:260
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    ">=",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:271
		{
			yyVAL.node = yyDollar[1].node
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:275
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "+",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:283
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "-",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:294
		{
			yyVAL.node = yyDollar[1].node
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:298
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "*",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:306
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "/",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:314
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "%",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:325
		{
			yyVAL.node = yyDollar[1].node
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:329
		{
			yyVAL.node = &Node{
				Type:     NodeBinOp,
				Token:    "^",
				Children: []*Node{yyDollar[1].node, yyDollar[3].node},
			}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:340
		{
			yyVAL.node = yyDollar[1].node
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line g.y:344
		{
			yyVAL.node = &Node{
				Type:     NodeUnaryOp,
				Token:    "+",
				Children: []*Node{yyDollar[2].node},
			}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line g.y:352
		{
			yyVAL.node = &Node{
				Type:     NodeUnaryOp,
				Token:    "-",
				Children: []*Node{yyDollar[2].node},
			}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line g.y:360
		{
			yyVAL.node = &Node{
				Type:     NodeUnaryOp,
				Token:    "!",
				Children: []*Node{yyDollar[2].node},
			}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:371
		{
			yyVAL.node = &Node{
				Type:  NodeIdent,
				Token: yyDollar[1].str,
			}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:378
		{
			yyVAL.node = &Node{
				Type:  NodeNumber,
				Token: yyDollar[1].str,
			}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:385
		{
			yyVAL.node = &Node{
				Type:  NodeBool,
				Token: "true",
			}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line g.y:392
		{
			yyVAL.node = &Node{
				Type:  NodeBool,
				Token: "false",
			}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line g.y:399
		{
			yyVAL.node = yyDollar[2].node
		}
	}
	goto yystack /* stack new state and value */
}
