// Code generated by mk_attr. DO NOT EDIT.

package combat

import (
	"github.com/legamerdc/game/attr"
)

// Compile-time interface check.
var _ attr.AttributeSet = (*DemoAttributeSet)(nil)

// ---------- Set ID ----------

const DemoSetID uint32 = 1

// ---------- Field Indices ----------

const (
	DemoField_Hp          uint16 = 0
	DemoField_Mana        uint16 = 1
	DemoField_MaxHp       uint16 = 2
	DemoField_MaxMana     uint16 = 3
	DemoField_Attack      uint16 = 4
	DemoField_Defense     uint16 = 5
	DemoField_AttackRange uint16 = 6
	DemoField_AttackSpeed uint16 = 7
	DemoFieldCount        uint16 = 8
)

// ---------- Global AttrKeys (SetID<<16 | FieldIndex) ----------

const (
	DemoAttrKey_Hp          uint32 = (DemoSetID << 16) | uint32(DemoField_Hp)
	DemoAttrKey_Mana        uint32 = (DemoSetID << 16) | uint32(DemoField_Mana)
	DemoAttrKey_MaxHp       uint32 = (DemoSetID << 16) | uint32(DemoField_MaxHp)
	DemoAttrKey_MaxMana     uint32 = (DemoSetID << 16) | uint32(DemoField_MaxMana)
	DemoAttrKey_Attack      uint32 = (DemoSetID << 16) | uint32(DemoField_Attack)
	DemoAttrKey_Defense     uint32 = (DemoSetID << 16) | uint32(DemoField_Defense)
	DemoAttrKey_AttackRange uint32 = (DemoSetID << 16) | uint32(DemoField_AttackRange)
	DemoAttrKey_AttackSpeed uint32 = (DemoSetID << 16) | uint32(DemoField_AttackSpeed)
)

// ---------- Dirty Bits ----------

const (
	DemoDirty_Hp          uint64 = 1 << DemoField_Hp
	DemoDirty_Mana        uint64 = 1 << DemoField_Mana
	DemoDirty_MaxHp       uint64 = 1 << DemoField_MaxHp
	DemoDirty_MaxMana     uint64 = 1 << DemoField_MaxMana
	DemoDirty_Attack      uint64 = 1 << DemoField_Attack
	DemoDirty_Defense     uint64 = 1 << DemoField_Defense
	DemoDirty_AttackRange uint64 = 1 << DemoField_AttackRange
	DemoDirty_AttackSpeed uint64 = 1 << DemoField_AttackSpeed
)

// ---------- Struct ----------

type DemoAttributeSet struct {
	dirty uint64

	// AttributeValue
	Hp          attr.Value
	Mana        attr.Value
	MaxHp       attr.Value
	MaxMana     attr.Value
	Attack      attr.Value
	Defense     attr.Value
	AttackRange attr.Value
	AttackSpeed attr.Value
}

// ---------- Bind ----------

// GetDemoAttrs retrieves the typed *DemoAttributeSet from an attr.Map.
// Returns nil if the set is not registered.
func GetDemoAttrs(m *attr.Map) *DemoAttributeSet {
	if s := m.Get(DemoSetID); s != nil {
		return s.(*DemoAttributeSet)
	}
	return nil
}

// ---------- Interface: attr.AttributeSet ----------

func (s *DemoAttributeSet) SetID() uint32                { return DemoSetID }
func (s *DemoAttributeSet) FieldCount() uint16           { return DemoFieldCount }
func (s *DemoAttributeSet) Dirty() uint64                { return s.dirty }
func (s *DemoAttributeSet) IsDirty() bool                { return s.dirty != 0 }
func (s *DemoAttributeSet) IsFieldDirty(bit uint64) bool { return s.dirty&bit != 0 }
func (s *DemoAttributeSet) ClearDirty()                  { s.dirty = 0 }

// ==============================================================
// Typed Accessors
// ==============================================================

// ---------- Hp (AttributeValue) ----------

func (s *DemoAttributeSet) GetHp() attr.Value     { return s.Hp }
func (s *DemoAttributeSet) GetHpBase() float64    { return s.Hp.Base }
func (s *DemoAttributeSet) GetHpCurrent() float64 { return s.Hp.Current }
func (s *DemoAttributeSet) SetHpBase(v float64) {
	s.dirty |= DemoDirty_Hp
	s.Hp.Base = v
}
func (s *DemoAttributeSet) SetHpCurrent(v float64) {
	s.dirty |= DemoDirty_Hp
	s.Hp.Current = v
}

// ---------- Mana (AttributeValue) ----------

func (s *DemoAttributeSet) GetMana() attr.Value     { return s.Mana }
func (s *DemoAttributeSet) GetManaBase() float64    { return s.Mana.Base }
func (s *DemoAttributeSet) GetManaCurrent() float64 { return s.Mana.Current }
func (s *DemoAttributeSet) SetManaBase(v float64) {
	s.dirty |= DemoDirty_Mana
	s.Mana.Base = v
}
func (s *DemoAttributeSet) SetManaCurrent(v float64) {
	s.dirty |= DemoDirty_Mana
	s.Mana.Current = v
}

// ---------- MaxHp (AttributeValue) ----------

func (s *DemoAttributeSet) GetMaxHp() attr.Value     { return s.MaxHp }
func (s *DemoAttributeSet) GetMaxHpBase() float64    { return s.MaxHp.Base }
func (s *DemoAttributeSet) GetMaxHpCurrent() float64 { return s.MaxHp.Current }
func (s *DemoAttributeSet) SetMaxHpBase(v float64) {
	s.dirty |= DemoDirty_MaxHp
	s.MaxHp.Base = v
}
func (s *DemoAttributeSet) SetMaxHpCurrent(v float64) {
	s.dirty |= DemoDirty_MaxHp
	s.MaxHp.Current = v
}

// ---------- MaxMana (AttributeValue) ----------

func (s *DemoAttributeSet) GetMaxMana() attr.Value     { return s.MaxMana }
func (s *DemoAttributeSet) GetMaxManaBase() float64    { return s.MaxMana.Base }
func (s *DemoAttributeSet) GetMaxManaCurrent() float64 { return s.MaxMana.Current }
func (s *DemoAttributeSet) SetMaxManaBase(v float64) {
	s.dirty |= DemoDirty_MaxMana
	s.MaxMana.Base = v
}
func (s *DemoAttributeSet) SetMaxManaCurrent(v float64) {
	s.dirty |= DemoDirty_MaxMana
	s.MaxMana.Current = v
}

// ---------- Attack (AttributeValue) ----------

func (s *DemoAttributeSet) GetAttack() attr.Value     { return s.Attack }
func (s *DemoAttributeSet) GetAttackBase() float64    { return s.Attack.Base }
func (s *DemoAttributeSet) GetAttackCurrent() float64 { return s.Attack.Current }
func (s *DemoAttributeSet) SetAttackBase(v float64) {
	s.dirty |= DemoDirty_Attack
	s.Attack.Base = v
}
func (s *DemoAttributeSet) SetAttackCurrent(v float64) {
	s.dirty |= DemoDirty_Attack
	s.Attack.Current = v
}

// ---------- Defense (AttributeValue) ----------

func (s *DemoAttributeSet) GetDefense() attr.Value     { return s.Defense }
func (s *DemoAttributeSet) GetDefenseBase() float64    { return s.Defense.Base }
func (s *DemoAttributeSet) GetDefenseCurrent() float64 { return s.Defense.Current }
func (s *DemoAttributeSet) SetDefenseBase(v float64) {
	s.dirty |= DemoDirty_Defense
	s.Defense.Base = v
}
func (s *DemoAttributeSet) SetDefenseCurrent(v float64) {
	s.dirty |= DemoDirty_Defense
	s.Defense.Current = v
}

// ---------- AttackRange (AttributeValue) ----------

func (s *DemoAttributeSet) GetAttackRange() attr.Value     { return s.AttackRange }
func (s *DemoAttributeSet) GetAttackRangeBase() float64    { return s.AttackRange.Base }
func (s *DemoAttributeSet) GetAttackRangeCurrent() float64 { return s.AttackRange.Current }
func (s *DemoAttributeSet) SetAttackRangeBase(v float64) {
	s.dirty |= DemoDirty_AttackRange
	s.AttackRange.Base = v
}
func (s *DemoAttributeSet) SetAttackRangeCurrent(v float64) {
	s.dirty |= DemoDirty_AttackRange
	s.AttackRange.Current = v
}

// ---------- AttackSpeed (AttributeValue) ----------

func (s *DemoAttributeSet) GetAttackSpeed() attr.Value     { return s.AttackSpeed }
func (s *DemoAttributeSet) GetAttackSpeedBase() float64    { return s.AttackSpeed.Base }
func (s *DemoAttributeSet) GetAttackSpeedCurrent() float64 { return s.AttackSpeed.Current }
func (s *DemoAttributeSet) SetAttackSpeedBase(v float64) {
	s.dirty |= DemoDirty_AttackSpeed
	s.AttackSpeed.Base = v
}
func (s *DemoAttributeSet) SetAttackSpeedCurrent(v float64) {
	s.dirty |= DemoDirty_AttackSpeed
	s.AttackSpeed.Current = v
}

// ==============================================================
// Generic Field Access (by FieldIndex)
// ==============================================================

// GetCurrent returns the effective value: ScalarValue -> value, AttributeValue -> Current.
func (s *DemoAttributeSet) GetCurrent(field uint16) (float64, bool) {
	switch field {
	case DemoField_Hp:
		return s.Hp.Current, true
	case DemoField_Mana:
		return s.Mana.Current, true
	case DemoField_MaxHp:
		return s.MaxHp.Current, true
	case DemoField_MaxMana:
		return s.MaxMana.Current, true
	case DemoField_Attack:
		return s.Attack.Current, true
	case DemoField_Defense:
		return s.Defense.Current, true
	case DemoField_AttackRange:
		return s.AttackRange.Current, true
	case DemoField_AttackSpeed:
		return s.AttackSpeed.Current, true
	}
	return 0, false
}

// GetBase returns the base value: ScalarValue -> value, AttributeValue -> Base.
func (s *DemoAttributeSet) GetBase(field uint16) (float64, bool) {
	switch field {
	case DemoField_Hp:
		return s.Hp.Base, true
	case DemoField_Mana:
		return s.Mana.Base, true
	case DemoField_MaxHp:
		return s.MaxHp.Base, true
	case DemoField_MaxMana:
		return s.MaxMana.Base, true
	case DemoField_Attack:
		return s.Attack.Base, true
	case DemoField_Defense:
		return s.Defense.Base, true
	case DemoField_AttackRange:
		return s.AttackRange.Base, true
	case DemoField_AttackSpeed:
		return s.AttackSpeed.Base, true
	}
	return 0, false
}

// SetBase sets the base value and marks the field dirty.
func (s *DemoAttributeSet) SetBase(field uint16, v float64) bool {
	switch field {
	case DemoField_Hp:
		s.SetHpBase(v)
		return true
	case DemoField_Mana:
		s.SetManaBase(v)
		return true
	case DemoField_MaxHp:
		s.SetMaxHpBase(v)
		return true
	case DemoField_MaxMana:
		s.SetMaxManaBase(v)
		return true
	case DemoField_Attack:
		s.SetAttackBase(v)
		return true
	case DemoField_Defense:
		s.SetDefenseBase(v)
		return true
	case DemoField_AttackRange:
		s.SetAttackRangeBase(v)
		return true
	case DemoField_AttackSpeed:
		s.SetAttackSpeedBase(v)
		return true
	}
	return false
}

// SetCurrent sets the current value and marks the field dirty.
func (s *DemoAttributeSet) SetCurrent(field uint16, v float64) bool {
	switch field {
	case DemoField_Hp:
		s.SetHpCurrent(v)
		return true
	case DemoField_Mana:
		s.SetManaCurrent(v)
		return true
	case DemoField_MaxHp:
		s.SetMaxHpCurrent(v)
		return true
	case DemoField_MaxMana:
		s.SetMaxManaCurrent(v)
		return true
	case DemoField_Attack:
		s.SetAttackCurrent(v)
		return true
	case DemoField_Defense:
		s.SetDefenseCurrent(v)
		return true
	case DemoField_AttackRange:
		s.SetAttackRangeCurrent(v)
		return true
	case DemoField_AttackSpeed:
		s.SetAttackSpeedCurrent(v)
		return true
	}
	return false
}
